apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/anuj/springbootjava:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/anuj/springbootjava:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: springbootjava
        chartPath: charts/springbootjava
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/anuj/springbootjava'
          image.tag: '{{.DIGEST_HEX}}'
